### ISSUE TITLE
[tinyphysics] Model is not robust to out of distribution data

### ISSUE THREAD

**Issue by nuwandavek** [commaai/controls_challenge#1]
The current model has a couple of issues:
1. The model is not robust to out of distribution steer values (like all 0, or all a constant value). This makes it behave unnaturally to those inputs. Augmenting training data should fix this.
2. The road roll is very highly correlated to the lateral accel. The above steer augmentation should fix this as well.

**Comment by omarrayyann** [comment]
Could you elaborate by augmenting the training data in this context

**Comment by nuwandavek** [comment]
> Could you elaborate on what you mean by augmenting the training data in this context
The training procedure for the "car" model is as follows:
1. A filtered subset of real drives was taken (with road roll, target acceleration etc).
2. A "car-agent" was driven in a simulator, with the above targets, and lots of varying noise.
3. A model was trained to take in the driving inputs, and predict the car's response in the simulator.

As a consequence, the model has not really seen any drives with all zero or a constant value input. But this input is trivial to provide in the controller in this challenge. So, we need to augment Step-1 with more synthetic drives so that the eventual model is robust to such inputs.
