### ISSUE TITLE
CONTROL_START_IDX

### ISSUE THREAD

**Issue by omarrayyann** [commaai/controls_challenge#12]
Shouldn't ```CONTEXT_LENGTH``` in the reset and rollout functions be replaced with ```CONTROL_START_IDX```

<img width="293" alt="Screenshot 2024-05-22 at 9 23 07 AM" src="https://github.com/commaai/controls_challenge/assets/77675540/a36a58f0-8dae-4728-9a6d-773ac5cfd2db">

**Comment by nuwandavek** [comment]
No, I think this is correct? The step_idx needs to be such that the context is filled. But it can be before `CONTROL_START_IDX`. This is intended to "warm up" the model/controller if necessary. Might make more sense with this: https://github.com/commaai/controls_challenge/pull/13
